/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */
import type {
  ArtifactDto,
  CaptionResponse,
  ChatRequest,
  ChatResponse,
  DemoVisionCaptionBody,
  DemoVisionDetectBody,
  DemoVisionOcrBody,
  DetectionResponse,
  Engagement,
  ExperienceDto,
  GoalDto,
  ListExperiencesParams,
  MediaAssetDto,
  MyInfo,
  OcrResponse,
  Project,
  Skill,
  SkillMaturityResponse,
  SkillRelatedResponse,
  SkillTimelineResponse,
  SynthesizeRequest,
  Voice
} from './models';

import { customFetch } from './fetcher';
export type getMyInfoResponse200 = {
  data: MyInfo
  status: 200
}

export type getMyInfoResponse404 = {
  data: void
  status: 404
}

export type getMyInfoResponseSuccess = (getMyInfoResponse200) & {
  headers: Headers;
};
export type getMyInfoResponseError = (getMyInfoResponse404) & {
  headers: Headers;
};

export type getMyInfoResponse = (getMyInfoResponseSuccess | getMyInfoResponseError)

export const getGetMyInfoUrl = () => {




  return `/api/resume/me`
}

export const getMyInfo = async ( options?: RequestInit): Promise<getMyInfoResponse> => {

  return customFetch<getMyInfoResponse>(getGetMyInfoUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type getEngagementsResponse200 = {
  data: Engagement[]
  status: 200
}

export type getEngagementsResponseSuccess = (getEngagementsResponse200) & {
  headers: Headers;
};
;

export type getEngagementsResponse = (getEngagementsResponseSuccess)

export const getGetEngagementsUrl = () => {




  return `/api/resume/engagements`
}

export const getEngagements = async ( options?: RequestInit): Promise<getEngagementsResponse> => {

  return customFetch<getEngagementsResponse>(getGetEngagementsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type getEngagementResponse200 = {
  data: Engagement
  status: 200
}

export type getEngagementResponse404 = {
  data: void
  status: 404
}

export type getEngagementResponseSuccess = (getEngagementResponse200) & {
  headers: Headers;
};
export type getEngagementResponseError = (getEngagementResponse404) & {
  headers: Headers;
};

export type getEngagementResponse = (getEngagementResponseSuccess | getEngagementResponseError)

export const getGetEngagementUrl = (id: string,) => {




  return `/api/resume/engagements/${id}`
}

export const getEngagement = async (id: string, options?: RequestInit): Promise<getEngagementResponse> => {

  return customFetch<getEngagementResponse>(getGetEngagementUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export type getProjectsResponse200 = {
  data: Project[]
  status: 200
}

export type getProjectsResponseSuccess = (getProjectsResponse200) & {
  headers: Headers;
};
;

export type getProjectsResponse = (getProjectsResponseSuccess)

export const getGetProjectsUrl = () => {




  return `/api/resume/projects`
}

export const getProjects = async ( options?: RequestInit): Promise<getProjectsResponse> => {

  return customFetch<getProjectsResponse>(getGetProjectsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type getProjectResponse200 = {
  data: Project
  status: 200
}

export type getProjectResponse404 = {
  data: void
  status: 404
}

export type getProjectResponseSuccess = (getProjectResponse200) & {
  headers: Headers;
};
export type getProjectResponseError = (getProjectResponse404) & {
  headers: Headers;
};

export type getProjectResponse = (getProjectResponseSuccess | getProjectResponseError)

export const getGetProjectUrl = (id: string,) => {




  return `/api/resume/projects/${id}`
}

export const getProject = async (id: string, options?: RequestInit): Promise<getProjectResponse> => {

  return customFetch<getProjectResponse>(getGetProjectUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export type getSkillsResponse200 = {
  data: Skill[]
  status: 200
}

export type getSkillsResponseSuccess = (getSkillsResponse200) & {
  headers: Headers;
};
;

export type getSkillsResponse = (getSkillsResponseSuccess)

export const getGetSkillsUrl = () => {




  return `/api/resume/skills`
}

export const getSkills = async ( options?: RequestInit): Promise<getSkillsResponse> => {

  return customFetch<getSkillsResponse>(getGetSkillsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type getSkillTimelineResponse200 = {
  data: SkillTimelineResponse
  status: 200
}

export type getSkillTimelineResponse404 = {
  data: void
  status: 404
}

export type getSkillTimelineResponseSuccess = (getSkillTimelineResponse200) & {
  headers: Headers;
};
export type getSkillTimelineResponseError = (getSkillTimelineResponse404) & {
  headers: Headers;
};

export type getSkillTimelineResponse = (getSkillTimelineResponseSuccess | getSkillTimelineResponseError)

export const getGetSkillTimelineUrl = (id: string,) => {




  return `/api/skills/${id}/timeline`
}

export const getSkillTimeline = async (id: string, options?: RequestInit): Promise<getSkillTimelineResponse> => {

  return customFetch<getSkillTimelineResponse>(getGetSkillTimelineUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export type getSkillRelatedResponse200 = {
  data: SkillRelatedResponse
  status: 200
}

export type getSkillRelatedResponse404 = {
  data: void
  status: 404
}

export type getSkillRelatedResponseSuccess = (getSkillRelatedResponse200) & {
  headers: Headers;
};
export type getSkillRelatedResponseError = (getSkillRelatedResponse404) & {
  headers: Headers;
};

export type getSkillRelatedResponse = (getSkillRelatedResponseSuccess | getSkillRelatedResponseError)

export const getGetSkillRelatedUrl = (id: string,) => {




  return `/api/skills/${id}/related`
}

export const getSkillRelated = async (id: string, options?: RequestInit): Promise<getSkillRelatedResponse> => {

  return customFetch<getSkillRelatedResponse>(getGetSkillRelatedUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export type getSkillMaturityResponse200 = {
  data: SkillMaturityResponse
  status: 200
}

export type getSkillMaturityResponse404 = {
  data: void
  status: 404
}

export type getSkillMaturityResponseSuccess = (getSkillMaturityResponse200) & {
  headers: Headers;
};
export type getSkillMaturityResponseError = (getSkillMaturityResponse404) & {
  headers: Headers;
};

export type getSkillMaturityResponse = (getSkillMaturityResponseSuccess | getSkillMaturityResponseError)

export const getGetSkillMaturityUrl = (id: string,) => {




  return `/api/skills/${id}/maturity`
}

export const getSkillMaturity = async (id: string, options?: RequestInit): Promise<getSkillMaturityResponse> => {

  return customFetch<getSkillMaturityResponse>(getGetSkillMaturityUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export type listMediaResponse200 = {
  data: MediaAssetDto[]
  status: 200
}

export type listMediaResponseSuccess = (listMediaResponse200) & {
  headers: Headers;
};
;

export type listMediaResponse = (listMediaResponseSuccess)

export const getListMediaUrl = () => {




  return `/api/media`
}

export const listMedia = async ( options?: RequestInit): Promise<listMediaResponse> => {

  return customFetch<listMediaResponse>(getListMediaUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type getMediaResponse200 = {
  data: MediaAssetDto
  status: 200
}

export type getMediaResponse404 = {
  data: void
  status: 404
}

export type getMediaResponseSuccess = (getMediaResponse200) & {
  headers: Headers;
};
export type getMediaResponseError = (getMediaResponse404) & {
  headers: Headers;
};

export type getMediaResponse = (getMediaResponseSuccess | getMediaResponseError)

export const getGetMediaUrl = (id: string,) => {




  return `/api/media/${id}`
}

export const getMedia = async (id: string, options?: RequestInit): Promise<getMediaResponse> => {

  return customFetch<getMediaResponse>(getGetMediaUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export type downloadMediaResponse404 = {
  data: void
  status: 404
}

;
export type downloadMediaResponseError = (downloadMediaResponse404) & {
  headers: Headers;
};

export type downloadMediaResponse = (downloadMediaResponseError)

export const getDownloadMediaUrl = (id: string,) => {




  return `/api/media/${id}/blob`
}

export const downloadMedia = async (id: string, options?: RequestInit): Promise<downloadMediaResponse> => {

  return customFetch<downloadMediaResponse>(getDownloadMediaUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export type listArtifactsResponse200 = {
  data: ArtifactDto[]
  status: 200
}

export type listArtifactsResponseSuccess = (listArtifactsResponse200) & {
  headers: Headers;
};
;

export type listArtifactsResponse = (listArtifactsResponseSuccess)

export const getListArtifactsUrl = () => {




  return `/api/artifacts`
}

export const listArtifacts = async ( options?: RequestInit): Promise<listArtifactsResponse> => {

  return customFetch<listArtifactsResponse>(getListArtifactsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type getArtifactResponse200 = {
  data: ArtifactDto
  status: 200
}

export type getArtifactResponse404 = {
  data: void
  status: 404
}

export type getArtifactResponseSuccess = (getArtifactResponse200) & {
  headers: Headers;
};
export type getArtifactResponseError = (getArtifactResponse404) & {
  headers: Headers;
};

export type getArtifactResponse = (getArtifactResponseSuccess | getArtifactResponseError)

export const getGetArtifactUrl = (id: string,) => {




  return `/api/artifacts/${id}`
}

export const getArtifact = async (id: string, options?: RequestInit): Promise<getArtifactResponse> => {

  return customFetch<getArtifactResponse>(getGetArtifactUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export type listGoalsResponse200 = {
  data: GoalDto[]
  status: 200
}

export type listGoalsResponseSuccess = (listGoalsResponse200) & {
  headers: Headers;
};
;

export type listGoalsResponse = (listGoalsResponseSuccess)

export const getListGoalsUrl = () => {




  return `/api/goals`
}

export const listGoals = async ( options?: RequestInit): Promise<listGoalsResponse> => {

  return customFetch<listGoalsResponse>(getListGoalsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type getGoalResponse200 = {
  data: GoalDto
  status: 200
}

export type getGoalResponse404 = {
  data: void
  status: 404
}

export type getGoalResponseSuccess = (getGoalResponse200) & {
  headers: Headers;
};
export type getGoalResponseError = (getGoalResponse404) & {
  headers: Headers;
};

export type getGoalResponse = (getGoalResponseSuccess | getGoalResponseError)

export const getGetGoalUrl = (id: string,) => {




  return `/api/goals/${id}`
}

export const getGoal = async (id: string, options?: RequestInit): Promise<getGoalResponse> => {

  return customFetch<getGoalResponse>(getGetGoalUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export type listExperiencesResponse200 = {
  data: ExperienceDto[]
  status: 200
}

export type listExperiencesResponseSuccess = (listExperiencesResponse200) & {
  headers: Headers;
};
;

export type listExperiencesResponse = (listExperiencesResponseSuccess)

export const getListExperiencesUrl = (params?: ListExperiencesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/experiences?${stringifiedParams}` : `/api/experiences`
}

export const listExperiences = async (params?: ListExperiencesParams, options?: RequestInit): Promise<listExperiencesResponse> => {

  return customFetch<listExperiencesResponse>(getListExperiencesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export type demoChatSendMessageResponse200 = {
  data: ChatResponse
  status: 200
}

export type demoChatSendMessageResponseSuccess = (demoChatSendMessageResponse200) & {
  headers: Headers;
};
;

export type demoChatSendMessageResponse = (demoChatSendMessageResponseSuccess)

export const getDemoChatSendMessageUrl = () => {




  return `/api/demos/chat/messages`
}

export const demoChatSendMessage = async (chatRequest: ChatRequest, options?: RequestInit): Promise<demoChatSendMessageResponse> => {

  return customFetch<demoChatSendMessageResponse>(getDemoChatSendMessageUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      chatRequest,)
  }
);}



export type demoTextToSpeechGetVoicesResponse200 = {
  data: Voice[]
  status: 200
}

export type demoTextToSpeechGetVoicesResponseSuccess = (demoTextToSpeechGetVoicesResponse200) & {
  headers: Headers;
};
;

export type demoTextToSpeechGetVoicesResponse = (demoTextToSpeechGetVoicesResponseSuccess)

export const getDemoTextToSpeechGetVoicesUrl = () => {




  return `/api/demos/text-to-speech/voices`
}

export const demoTextToSpeechGetVoices = async ( options?: RequestInit): Promise<demoTextToSpeechGetVoicesResponse> => {

  return customFetch<demoTextToSpeechGetVoicesResponse>(getDemoTextToSpeechGetVoicesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type demoTextToSpeechSynthesizeResponse200 = {
  data: void
  status: 200
}

export type demoTextToSpeechSynthesizeResponseSuccess = (demoTextToSpeechSynthesizeResponse200) & {
  headers: Headers;
};
;

export type demoTextToSpeechSynthesizeResponse = (demoTextToSpeechSynthesizeResponseSuccess)

export const getDemoTextToSpeechSynthesizeUrl = () => {




  return `/api/demos/text-to-speech/syntheses`
}

export const demoTextToSpeechSynthesize = async (synthesizeRequest: SynthesizeRequest, options?: RequestInit): Promise<demoTextToSpeechSynthesizeResponse> => {

  return customFetch<demoTextToSpeechSynthesizeResponse>(getDemoTextToSpeechSynthesizeUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      synthesizeRequest,)
  }
);}



export type demoVisionCaptionResponse200 = {
  data: CaptionResponse
  status: 200
}

export type demoVisionCaptionResponseSuccess = (demoVisionCaptionResponse200) & {
  headers: Headers;
};
;

export type demoVisionCaptionResponse = (demoVisionCaptionResponseSuccess)

export const getDemoVisionCaptionUrl = () => {




  return `/api/demos/vision/captions`
}

export const demoVisionCaption = async (demoVisionCaptionBody: DemoVisionCaptionBody, options?: RequestInit): Promise<demoVisionCaptionResponse> => {
    const formData = new FormData();
formData.append(`image`, demoVisionCaptionBody.image);

  return customFetch<demoVisionCaptionResponse>(getDemoVisionCaptionUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body:
      formData,
  }
);}



export type demoVisionOcrResponse200 = {
  data: OcrResponse
  status: 200
}

export type demoVisionOcrResponseSuccess = (demoVisionOcrResponse200) & {
  headers: Headers;
};
;

export type demoVisionOcrResponse = (demoVisionOcrResponseSuccess)

export const getDemoVisionOcrUrl = () => {




  return `/api/demos/vision/ocr`
}

export const demoVisionOcr = async (demoVisionOcrBody: DemoVisionOcrBody, options?: RequestInit): Promise<demoVisionOcrResponse> => {
    const formData = new FormData();
formData.append(`image`, demoVisionOcrBody.image);

  return customFetch<demoVisionOcrResponse>(getDemoVisionOcrUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body:
      formData,
  }
);}



export type demoVisionDetectResponse200 = {
  data: DetectionResponse
  status: 200
}

export type demoVisionDetectResponseSuccess = (demoVisionDetectResponse200) & {
  headers: Headers;
};
;

export type demoVisionDetectResponse = (demoVisionDetectResponseSuccess)

export const getDemoVisionDetectUrl = () => {




  return `/api/demos/vision/detections`
}

export const demoVisionDetect = async (demoVisionDetectBody: DemoVisionDetectBody, options?: RequestInit): Promise<demoVisionDetectResponse> => {
    const formData = new FormData();
formData.append(`image`, demoVisionDetectBody.image);

  return customFetch<demoVisionDetectResponse>(getDemoVisionDetectUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body:
      formData,
  }
);}
