/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */
import type {
  WeatherForecast
} from './models';

import { customFetch } from './fetcher';
export type getWeatherForecastResponse200 = {
  data: WeatherForecast[]
  status: 200
}

export type getWeatherForecastResponseSuccess = (getWeatherForecastResponse200) & {
  headers: Headers;
};
;

export type getWeatherForecastResponse = (getWeatherForecastResponseSuccess)

export const getGetWeatherForecastUrl = () => {




  return `/api/weatherforecast`
}

export const getWeatherForecast = async ( options?: RequestInit): Promise<getWeatherForecastResponse> => {

  return customFetch<getWeatherForecastResponse>(getGetWeatherForecastUrl(),
  {
    ...options,
    method: 'GET'


  }
);}
