/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export type ArtifactKind = typeof ArtifactKind[keyof typeof ArtifactKind];


export const ArtifactKind = {
  Repo: 'Repo',
  PullRequest: 'PullRequest',
  Issue: 'Issue',
  BlogPost: 'BlogPost',
  Talk: 'Talk',
  Video: 'Video',
  Certification: 'Certification',
  Paper: 'Paper',
} as const;
