/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ArtifactKind } from './artifactKind';
import type { ArtifactSkillLinkDto } from './artifactSkillLinkDto';

export interface ArtifactDto {
  id: string;
  kind: ArtifactKind;
  url: string;
  title: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  producedOn?: string | null;
  archived?: boolean;
  linkedProjectIds: string[];
  linkedEngagementIds: string[];
  linkedSkills: ArtifactSkillLinkDto[];
}
