/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ArtifactRole } from './artifactRole';

export interface ArtifactSkillLinkDto {
  skillId: string;
  role: ArtifactRole;
}
