/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export type ArtifactRole = typeof ArtifactRole[keyof typeof ArtifactRole];


export const ArtifactRole = {
  Evidence: 'Evidence',
  Output: 'Output',
  Source: 'Source',
} as const;
