/**
 * Generated by orval 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export interface Detection {
  x1: number;
  y1: number;
  x2: number;
  y2: number;
  label: string;
}
