/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Project } from './project';
import type { Skill } from './skill';

export interface Employment {
  id: string;
  company: string;
  title: string;
  startDate: string;
  /** @nullable */
  endDate?: string | null;
  /** @nullable */
  summary?: string | null;
  /** @nullable */
  location?: string | null;
  skills: Skill[];
  projects: Project[];
}
