/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export type EngagementKind = typeof EngagementKind[keyof typeof EngagementKind];


export const EngagementKind = {
  Employment: 'Employment',
  Study: 'Study',
  Hobby: 'Hobby',
  Volunteer: 'Volunteer',
  OpenSource: 'OpenSource',
} as const;
