/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */
import type { EngagementKind } from './engagementKind';
import type { Location } from './location';
import type { Project } from './project';
import type { Skill } from './skill';
import type { TitleEpochDto } from './titleEpochDto';

export interface Engagement {
  id: string;
  kind: EngagementKind;
  institution: string;
  /** @nullable */
  title?: string | null;
  titles: TitleEpochDto[];
  start: string;
  /** @nullable */
  end?: string | null;
  /** @nullable */
  summary?: string | null;
  location?: null | Location;
  skills: Skill[];
  projects: Project[];
}
