/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export type ExperienceKind = typeof ExperienceKind[keyof typeof ExperienceKind];


export const ExperienceKind = {
  Engagement: 'Engagement',
  Project: 'Project',
} as const;
