/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ExperienceKind } from './experienceKind';
import type { Location } from './location';

export interface ExperienceDto {
  id: string;
  kind: ExperienceKind;
  title: string;
  occurredOn: string;
  /** @nullable */
  endDate?: string | null;
  /** @nullable */
  engagementId?: string | null;
  /** @nullable */
  projectId?: string | null;
  skillIds: string[];
  location?: null | Location;
}
