/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export interface GoalProgressEntryDto {
  recordedAt: string;
  note: string;
  /** @nullable */
  linkedEventId?: string | null;
}
