/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */
import type { GoalProgressEntryDto } from './goalProgressEntryDto';
import type { GoalStatus } from './goalStatus';
import type { Maturity } from './maturity';

export interface GoalDto {
  id: string;
  /** @nullable */
  skillId?: string | null;
  targetMaturity: Maturity;
  /** @nullable */
  deadline?: string | null;
  motivation: string;
  status: GoalStatus;
  /** @nullable */
  resolvedAt?: string | null;
  /** @nullable */
  resolutionReason?: string | null;
  /** @nullable */
  evidenceArtifactId?: string | null;
  progress: GoalProgressEntryDto[];
}
