/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export * from './employment';
export * from './myInfo';
export * from './project';
export * from './skill';
export * from './skillCategory';
