/**
 * Generated by orval 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export type ListExperiencesParams = {
from?: string;
to?: string;
skillId?: string;
engagementId?: string;
};
