/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */
import type { LocationKind } from './locationKind';

export interface Location {
  kind: LocationKind;
  /** @nullable */
  city: string | null;
  /** @nullable */
  country: string | null;
}
