/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export type LocationKind = typeof LocationKind[keyof typeof LocationKind];


export const LocationKind = {
  Office: 'Office',
  Home: 'Home',
  Client: 'Client',
  Event: 'Event',
} as const;
