/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export type Maturity = typeof Maturity[keyof typeof Maturity];


export const Maturity = {
  Aware: 'Aware',
  Working: 'Working',
  Fluent: 'Fluent',
  Expert: 'Expert',
  Teaching: 'Teaching',
} as const;
