/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export type MediaRole = typeof MediaRole[keyof typeof MediaRole];


export const MediaRole = {
  Hero: 'Hero',
  Gallery: 'Gallery',
  Thumbnail: 'Thumbnail',
} as const;
