/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */
import type { MediaProjectLinkDto } from './mediaProjectLinkDto';

export interface MediaAssetDto {
  id: string;
  blobRef: string;
  mimeType: string;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  width?: number | string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  height?: number | string | null;
  altText: string;
  /** @nullable */
  caption?: string | null;
  archived?: boolean;
  linkedProjects: MediaProjectLinkDto[];
  linkedSkillIds: string[];
}
