/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */
import type { MediaProjectLinkDto } from './mediaProjectLinkDto';

export interface MediaAssetDto {
  id: string;
  blobRef: string;
  mimeType: string;
  /** @nullable */
  width?: number | null;
  /** @nullable */
  height?: number | null;
  altText: string;
  /** @nullable */
  caption?: string | null;
  archived?: boolean;
  linkedProjects: MediaProjectLinkDto[];
  linkedSkillIds: string[];
}
