/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export interface MyInfo {
  id: string;
  fullName: string;
  email: string;
  /** @nullable */
  tagline?: string | null;
  /** @nullable */
  bio?: string | null;
  /** @nullable */
  location?: string | null;
  /** @nullable */
  githubUrl?: string | null;
  /** @nullable */
  linkedInUrl?: string | null;
  /** @nullable */
  websiteUrl?: string | null;
}
