/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ProjectKind } from './projectKind';
import type { ProjectStatus } from './projectStatus';
import type { Skill } from './skill';

export interface Project {
  id: string;
  kind: ProjectKind;
  title: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  url?: string | null;
  /** @nullable */
  start?: string | null;
  /** @nullable */
  end?: string | null;
  status?: ProjectStatus;
  /** @nullable */
  engagementId?: string | null;
  /** @nullable */
  engagementInstitution?: string | null;
  skills: Skill[];
}
