/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export type ProjectKind = typeof ProjectKind[keyof typeof ProjectKind];


export const ProjectKind = {
  Professional: 'Professional',
  Personal: 'Personal',
  OpenSource: 'OpenSource',
  Academic: 'Academic',
} as const;
