/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Skill } from './skill';

export interface Project {
  id: string;
  title: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  url?: string | null;
  /** @nullable */
  startDate?: string | null;
  /** @nullable */
  endDate?: string | null;
  /** @nullable */
  employmentId?: string | null;
  /** @nullable */
  employmentCompany?: string | null;
  skills: Skill[];
}
