/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ArtifactKind } from './artifactKind';

export interface RegisterArtifactRequest {
  kind: ArtifactKind;
  url: string;
  title: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  producedOn?: string | null;
}
