/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Maturity } from './maturity';

export interface SetGoalRequest {
  /** @nullable */
  skillId?: string | null;
  targetMaturity: Maturity;
  /** @nullable */
  deadline?: string | null;
  motivation: string;
}
