/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Intensity } from './intensity';
import type { Maturity } from './maturity';
import type { SkillContextKind } from './skillContextKind';

export interface SkillTimelineEntryDto {
  kind: string;
  occurredOn: string;
  contextKind?: null | SkillContextKind;
  /** @nullable */
  contextId?: string | null;
  /** @nullable */
  contextLabel?: string | null;
  intensity?: null | Intensity;
  maturity?: null | Maturity;
  /** @nullable */
  otherSkillId?: string | null;
  /** @nullable */
  note?: string | null;
}
