/**
 * Generated by orval 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export type SkillContextKind = typeof SkillContextKind[keyof typeof SkillContextKind] | null;


export const SkillContextKind = {
  InEngagement: 'InEngagement',
  InProject: 'InProject',
  External: 'External',
} as const;
