/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export type SkillCategory = typeof SkillCategory[keyof typeof SkillCategory];


export const SkillCategory = {
  Language: 'Language',
  Framework: 'Framework',
  Tool: 'Tool',
  Platform: 'Platform',
  Method: 'Method',
  Domain: 'Domain',
  Other: 'Other',
} as const;
