/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export interface SkillRelatedEntry {
  skillId: string;
  name: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  count: number | string;
  /** @nullable */
  firstSeen?: string | null;
  /** @nullable */
  lastSeen?: string | null;
}
