/**
 * Generated by orval 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export interface SkillRelatedEntry {
  skillId: string;
  name: string;
  count: number;
  /** @nullable */
  firstSeen?: string | null;
  /** @nullable */
  lastSeen?: string | null;
}
