/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Maturity } from './maturity';
import type { SkillMaturityPointDto } from './skillMaturityPointDto';

export interface SkillMaturityResponse {
  skillId: string;
  current: Maturity;
  trajectory: SkillMaturityPointDto[];
}
