/**
 * Generated by orval 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SkillRelatedEntry } from './skillRelatedEntry';

export interface SkillRelatedResponse {
  skillId: string;
  related: SkillRelatedEntry[];
}
