/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Maturity } from './maturity';

export interface SkillMaturityPointDto {
  occurredOn: string;
  maturity: Maturity;
  /** @nullable */
  reason?: string | null;
}
