/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export interface TitleEpochDto {
  titleId: string;
  text: string;
  from: string;
  /** @nullable */
  to?: string | null;
}
