/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */
import type { IFormFile } from './iFormFile';

export type UploadMediaBody = {
  file?: IFormFile;
} & {
  altText?: string;
} & {
  caption?: string;
} & Required<Pick<{
  file?: IFormFile;
} & {
  altText?: string;
} & {
  caption?: string;
}, 'file' | 'altText'>>;
