/**
 * Generated by orval 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export interface Voice {
  id: string;
  name: string;
  language: string;
  gender: string;
}
