/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * LupiraWeb.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export interface WeatherForecast {
  date: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  temperatureC: number | string;
  /** @nullable */
  summary: string | null;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  temperatureF?: number | string;
}
